import {
  HOODIE_BLACK,
  HOODIE_BLUE,
  HOODIE_GREEN,
  HOODIE_RED,
  HOODIE_WHITE,
  SHIRT_BLUE,
  SHIRT_GREEN,
  SHIRT_GREY,
  SHIRT_ORANGE,
  SHIRT_YELLOW,
  TSHIRT_BLACK,
  TSHIRT_BLUE,
  TSHIRT_MAROON,
  TSHIRT_RED,
  TSHIRT_WHITE,
} from "./images";

export interface productListingDummyDataTypes {
  image: string;
  name: string;
  type: string;
  size: string;
  color: string;
  inStock: boolean;
  stock: number;
  price: number;
  qty?: number;
  id: string;
}

export const productListingDummyData: productListingDummyDataTypes[] = [
  {
    image: HOODIE_BLACK,
    name: "Classic Hoodie",
    type: "hoodie",
    size: "large",
    color: "black",
    inStock: true,
    price: 29.99,
    id: "hoodieblack",
    stock: 5,
  },
  {
    image: TSHIRT_BLACK,
    name: "Graphic T-Shirt",
    type: "t-shirt",
    size: "medium",
    color: "black",
    inStock: true,
    price: 19.99,
    id: "tshirtblack",
    stock: 4,
  },
  {
    image: SHIRT_BLUE,
    name: "Casual Shirt",
    type: "shirt",
    size: "small",
    color: "blue",
    inStock: false,
    price: 24.99,
    id: "shirtblue",
    stock: 0,
  },
  {
    image: HOODIE_BLUE,
    name: "Zip-Up Hoodie",
    type: "hoodie",
    size: "medium",
    color: "blue",
    inStock: true,
    price: 34.99,
    id: "hoodieblue",
    stock: 2,
  },
  {
    image: TSHIRT_BLUE,
    name: "V-Neck T-Shirt",
    type: "t-shirt",
    size: "large",
    color: "blue",
    inStock: true,
    price: 17.99,
    id: "tshirtblue",
    stock: 7,
  },
  {
    image: SHIRT_GREEN,
    name: "Slim Fit Shirt",
    type: "shirt",
    size: "large",
    color: "green",
    inStock: true,
    price: 27.99,
    id: "shirtgreen",
    stock: 3,
  },
  {
    image: HOODIE_GREEN,
    name: "Fleece Hoodie",
    type: "hoodie",
    size: "small",
    color: "green",
    inStock: false,
    price: 32.99,
    id: "hoodiegreen",
    stock: 0,
  },
  {
    image: TSHIRT_MAROON,
    name: "Pocket T-Shirt",
    type: "t-shirt",
    size: "small",
    color: "maroon",
    inStock: true,
    price: 15.99,
    id: "tshirtmaroon",
    stock: 6,
  },
  {
    image: SHIRT_GREY,
    name: "Linen Shirt",
    type: "shirt",
    size: "medium",
    color: "grey",
    inStock: false,
    price: 29.99,
    id: "shirtgrey",
    stock: 0,
  },
  {
    image: HOODIE_RED,
    name: "Pullover Hoodie",
    type: "hoodie",
    size: "large",
    color: "red",
    inStock: true,
    price: 39.99,
    id: "hoodiered",
    stock: 3,
  },
  {
    image: TSHIRT_RED,
    name: "Crew Neck T-Shirt",
    type: "t-shirt",
    size: "medium",
    color: "red",
    inStock: true,
    price: 16.99,
    id: "tshirtred",
    stock: 8,
  },
  {
    image: SHIRT_ORANGE,
    name: "Flannel Shirt",
    type: "shirt",
    size: "large",
    color: "orange",
    inStock: true,
    price: 31.99,
    id: "shirtorange",
    stock: 4,
  },
  {
    image: HOODIE_WHITE,
    name: "Cropped Hoodie",
    type: "hoodie",
    size: "medium",
    color: "white",
    inStock: false,
    price: 35.99,
    id: "hoodiewhite",
    stock: 0,
  },

  {
    image: TSHIRT_WHITE,
    name: "Printed T-Shirt",
    type: "t-shirt",
    size: "small",
    color: "white",
    inStock: true,
    price: 18.99,
    id: "tshirtwhite",
    stock: 5,
  },
  {
    image: SHIRT_YELLOW,
    name: "Denim Shirt",
    type: "shirt",
    size: "medium",
    color: "yellow",
    inStock: true,
    price: 36.99,
    id: "shirtyellow",
    stock: 3,
  },
];

export const productType: string[] = ["hoodie", "shirt", "t-shirt"];

export const productSize: string[] = ["small", "medium", "large"];
